### ISSUE TITLE
Not detecting className in React project

### ISSUE THREAD

**Issue by PabloCarmona** [hudochenkov/ecsstractor#14]
Hi! I'm trying to run eCSStractor in a React project, but I can't get any result in the process. Seems like the package aren't getting the classNames of the JSX code.

VS Code eCSStractor related settings:

```
"ecsstractor_port.attributes": "className",
"ecsstractor_port.destination": "tab"
```

JSX code:
```
<div className='global-info'>
    <p className='entity-name'>
            {entity.name}
          <span className='entity-name-separator'>•</span>
        <RefreshIcon style={{ marginRight: 8 }} />
    </p>
  <p>Saldo <span className='amount-number'>12</span></p>
</div>
```

Can anybody guess what I'm doing wrong? Thank you for your time and for this great package!

**Comment by hudochenkov** [comment]
This repository for Sublime Text plugin. For VS Code extension report to https://github.com/yurasovm/eCSStractor-for-VSCode
