### ISSUE TITLE
A question about the plugin name

### ISSUE THREAD

**Issue by anstarovoyt** [hudochenkov/ecsstractor#15]
Hi! I am going to build a similar plugin for WebStorm, and I want to make sure that it is ok to use the same plugin name (eCSStractor) for the plugin. What do you think about it? As far, as I understand, there are already VSCode plugins with the same name, but you plugin seems to be the first that used the name.

**Comment by hudochenkov** [comment]
Hey! Thanks for asking!

Sure, you can use it.
