### ISSUE TITLE
can we have ST-independant part of the code?

### ISSUE THREAD

**Issue by Alexey-T** [hudochenkov/ecsstractor#16]
To port this plugin to CudaText, I would ask for a separate Python module, which can extract the result, and which is **not importing ST** module.
The separate module, e.g. cssworker.py.
It must have all needed options as function arguments.
Function input: options + text (as list of strings, or just mul-line string).

can you help, please?

**Comment by hudochenkov** [comment]
I'm afraid I'm not going to help. I wrote this plugin long time ago. I don't know Python and don't use this plugin for a long time. Feel free to copy code you need.

**Comment by Alexey-T** [comment]
@ildarkhasanshin Is it interesting to you?

**Comment by ildarkhasanshin** [comment]
ок
