### ISSUE TITLE
Relative to cursor position

### ISSUE THREAD

**Issue by last1here** [hudochenkov/ecsstractor#7]
Add a way to only grab classes relative to the current cursor position? maybe as a second key binding

Example code:
```html
<div class="logo">
    <a class="logo__link">
        <img class="logo__image">
    </a>
</div>

<nav class="main_nav">
    <ul> ||
        <li class="main_nav__item">
            <a class="main_nav__link">Home</a>
        </li>
        <li class="main_nav__item">
            <a class="main_nav__link">About Us</a>
        </li>
        <li class="main_nav__item">
            <a class="main_nav__link">Contact Us</a>
        </li>
    </ul>
</nav>

<div class="phone">
    <p class="phone__number">
    </p>
</div>
```
and the cursor is at the `||` and then run eCSStractor the expected result would be

```css
.main_nav {
	&__item {
	}
	&__link {
	}
}
```
As oppose to returning all classes.

Thanks.

**Comment by hudochenkov** [comment]
You can execute standard command “Expand Selection to Tag” (Cmd+Shift-A) or “Match Tag Pair Outward” (Ctrl+D) if you have Emmet installed. Then run eCSStractor.

**Comment by last1here** [comment]
Yes I just noticed you can run it on selected code when I was reading through code, that's great, thanks.
